#! /bin/bash 
#  $1 = input data file
#  $2 = year input

# example use:
# bob@datapro:~/working_files/bin$ shortener /home/bbusey/working_files/ss_met/outputs/ss_met_at_11-0_avg.csv 2012


# Create a temp directory
tempdirectory="/home/$USER/tmp/"
if [ ! -d $tempdirectory ]; then
    mkdir $tempdirectory
fi
filename=$(basename $1)
# parse the file name & path
head -n4 $1 > $tempdirectory/$filename
grep "$2-" $1 >> $tempdirectory/$filename

mv $tempdirectory/$filename $1
